In [ ]:
# Импортируем библиотеки

import numpy as np
import pandas as pd
import seaborn as sns
sns.set_palette('husl')
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [ ]:
# Присвоим переменной «url» ссылку на датасет:

url = '/content/global_cars_dataset_synthetic.csv'

# создаем лист с названием столбцов:

cols = ['Car_ID', 'Brand', 'Manufacture_Year', 'Body_Type', 'Fuel_Type', 'Transmission', 'Engine_CC', 'Horsepower', 'Mileage_km_per_l', 'Price_USD', 'Manufacturing_Country']
# используем Pandas read_csv():

dataset = pd.read_csv(url, names = cols)

In [ ]:
dataset.shape

(301, 11)

In [ ]:
# отображаем первые 10 сстрок датасета
dataset.head(10)

,Car_ID,Brand,Manufacture_Year,Body_Type,Fuel_Type,Transmission,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Manufacturing_Country
0,Car_ID,Brand,Manufacture_Year,Body_Type,Fuel_Type,Transmission,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Manufacturing_Country
1,CAR_0001,Mercedes,2006,SUV,Petrol,Manual,4089,547,17,73407,USA
2,CAR_0002,Nissan,2023,Coupe,Petrol,Automatic,4618,167,25,79370,USA
3,CAR_0003,Nissan,2007,Hatchback,Diesel,Manual,1802,110,16,76549,China
4,CAR_0004,Nissan,2013,Coupe,Petrol,Manual,1835,373,16,48722,USA
5,CAR_0005,Hyundai,2009,Hatchback,Hybrid,Automatic,2332,145,28,83265,UK
6,CAR_0006,Tesla,2012,Coupe,Diesel,Automatic,2124,321,19,63134,UK
7,CAR_0007,Audi,2011,Hatchback,Petrol,Automatic,4527,342,29,74241,Japan
8,CAR_0008,Tesla,2016,SUV,Diesel,Automatic,1729,309,20,54364,China
9,CAR_0009,Audi,2017,Hatchback,Hybrid,Manual,1561,470,12,65750,Germany

In [ ]:
import mpl_toolkits.mplot3d
from sklearn import datasets
from sklearn.cluster import KMeans

Метод Pandas info()  выводит очень много информации о наборе данных - количество записей, количество ненулевых значений в каждом столбце, тип данных в столбце

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Car_ID                 301 non-null    object
 1   Brand                  301 non-null    object
 2   Manufacture_Year       301 non-null    object
 3   Body_Type              301 non-null    object
 4   Fuel_Type              301 non-null    object
 5   Transmission           301 non-null    object
 6   Engine_CC              301 non-null    object
 7   Horsepower             301 non-null    object
 8   Mileage_km_per_l       301 non-null    object
 9   Price_USD              301 non-null    object
 10  Manufacturing_Country  301 non-null    object
dtypes: object(11)
memory usage: 26.0+ KB

Pandas describe() используется для просмотра  основной статистической информации, таких как процентиль, среднее, стандартное отклонение и т.д. фрейма данных или ряда числовых значений:

In [ ]:
dataset.describe()

,Car_ID,Brand,Manufacture_Year,Body_Type,Fuel_Type,Transmission,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Manufacturing_Country
count,301,301,301,301,301,301,301,301,301,301,301
unique,301,11,22,6,5,3,288,221,22,301,7
top,CAR_0300,Nissan,2020,Sedan,Petrol,Manual,3117,165,17,118185,Germany
freq,1,41,27,70,77,155,2,4,21,1,55

In [ ]:
dataset['Brand'].unique()

array(['Brand', 'Mercedes', 'Nissan', 'Hyundai', 'Tesla', 'Audi', 'Honda',
       'Ford', 'Toyota', 'BMW', 'Kia'], dtype=object)

Теперь проверим количество строк, которое принадлежит каждому бренду:

In [ ]:

dataset['Brand'].value_counts()

Brand
Nissan      41
Ford        35
Tesla       35
Toyota      34
Hyundai     29
BMW         28
Mercedes    28
Kia         26
Audi        24
Honda       20
Brand        1
Name: count, dtype: int64

Преобразуем категориальные признаки в количественные

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
dataset[[ 'Car_ID', 'Brand', 'Manufacture_Year', 'Body_Type', 'Fuel_Type', 'Transmission', 'Engine_CC', 'Horsepower', 'Mileage_km_per_l', 'Price_USD', 'Manufacturing_Country']] = enc.fit_transform(dataset[[ 'Car_ID','Brand', 'Manufacture_Year', 'Body_Type', 'Fuel_Type', 'Transmission', 'Engine_CC', 'Horsepower', 'Mileage_km_per_l', 'Price_USD', 'Manufacturing_Country']])
dataset.head()

,Car_ID,Brand,Manufacture_Year,Body_Type,Fuel_Type,Transmission,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Manufacturing_Country
0,300.0,2.0,21.0,0.0,2.0,2.0,287.0,220.0,21.0,300.0,3.0
1,0.0,7.0,1.0,4.0,4.0,1.0,225.0,185.0,7.0,227.0,6.0
2,1.0,8.0,18.0,1.0,4.0,0.0,257.0,29.0,15.0,251.0,6.0
3,2.0,8.0,2.0,2.0,0.0,1.0,47.0,5.0,6.0,239.0,0.0
4,3.0,8.0,8.0,1.0,4.0,1.0,52.0,117.0,6.0,158.0,6.0

Разделение набора данных
Y - целевая переменная, которую предсказываем. Мы ищем зависимость этой переменной от соответствующих фич.

В X складываем весь набор данных без целевой переменной.

In [ ]:
X = dataset.drop(['Brand'], axis=1)
y = dataset['Brand']
print(f'X shape: {X.shape} | y shape: {y.shape} ')

X shape: (301, 10) | y shape: (301,)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=10)

Далее попробуем следующие алгоритмы:

Logistic Regression (LR)
Linear Discriminant Analysis (LDA)
K-Nearest Neighbors (KNN)
Classification and Regression Trees (CART)
Gaussian Naive Bayes (NB)
Support Vector Machines (SVM)

In [ ]:
models = []
models.append(('LR', LogisticRegression(solver='lbfgs', max_iter=1000)))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVC', SVC(gamma='auto')))

# оцениваем их метрики
results = []
model_names = []
for name, model in models:
  kfold = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
  cv_results = cross_val_score(model, X_train, y_train, cv=kfold, scoring='accuracy')
  results.append(cv_results)
  model_names.append(name)
  print('%s: %f (%f)' % (name, cv_results.mean(), cv_results.std()))

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(

LR: 0.095833 (0.059073)
LDA: 0.100000 (0.038188)
KNN: 0.100000 (0.067700)
CART: 0.079167 (0.082180)
NB: 0.112500 (0.079167)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(

SVC: 0.133333 (0.016667)

LR: 0.095833 (0.059073)
LDA: 0.100000 (0.038188)
KNN: 0.100000 (0.067700)
CART: 0.079167 (0.082180)
NB: 0.112500 (0.079167)

In [ ]:
sk_lda = LinearDiscriminantAnalysis(solver='eigen')
sk_lda.fit(X_train, y_train)
sk_lda_pred_res = sk_lda.predict(X_test)
sk_transformed = sk_lda.transform(X_train)
sk_lda_accuracy = accuracy_score(y_test, sk_lda_pred_res)

print(f'sk LDA accuracy: {sk_lda_accuracy}')
print(f'sk LDA prediction: {sk_lda_pred_res}')
print('sk transformed features', sk_transformed[:5].T, sep='\n')

sk LDA accuracy: 0.04918032786885246
sk LDA prediction: [ 5.  7.  1.  8.  6.  1.  8.  1.  3.  9. 10.  1. 10.  6.  6.  9.  7.  8.
  8. 10.  8.  8.  7.  5.  1. 10. 10.  8.  8. 10.  9.  1. 10. 10.  1.  6.
  0.  5.  1. 10.  7.  6.  9.  7.  8.  6.  6.  5.  9.  8. 10.  8.  6.  3.
  1.  8.  9.  1.  3.  6.  7.]
sk transformed features
[[ 0.93394046 -0.37172251  0.50088134  0.93776362 -0.41393717]
 [ 3.25359175  2.0462292   4.80239187  3.71943148  3.21427271]
 [ 0.06129001 -1.76008367 -0.202772    1.31056232 -0.10639709]
 [ 1.84932572  1.46748496  3.04885786  1.93032569  0.64057229]
 [ 0.27871453 -0.93870814 -0.35085164 -0.74163915 -2.86198743]
 [ 1.00373505 -0.20111471  0.12090848  2.34471262 -0.29225859]
 [-2.81862527  0.54920969 -1.59296077 -2.08849193 -0.71833485]
 [-2.23156607 -2.17397516 -2.41600535 -2.58203734 -0.90900456]
 [ 0.48416739  1.29490482 -0.43602079 -0.01144784 -0.27373211]
 [ 2.66408385  3.23122891  2.69137528  4.40467312  2.61322931]]

/usr/local/lib/python3.12/dist-packages/sklearn/covariance/_empirical_covariance.py:102: UserWarning: Only one sample available. You may want to reshape your data array
  warnings.warn(